const mtiLinks = [
"https://www.mtishows.com/elton-john-and-tim-rices-aida",
"https://www.mtishows.com/aint-misbehavin",
"https://www.mtishows.com/disneys-aladdin-dual-language-edition",
"https://www.mtishows.com/all-in-love",
"https://www.mtishows.com/the-all-night-strut",
"https://www.mtishows.com/the-all-night-strut-a-jumpin-jivin-jam",
"https://www.mtishows.com/amen-corner",
"https://www.mtishows.com/green-days-american-idiot",
"https://www.mtishows.com/annabelle-broom-the-unhappy-witch",
"https://www.mtishows.com/anne-of-green-gables",
"https://www.mtishows.com/annie",
"https://www.mtishows.com/annie-warbucks",
"https://www.mtishows.com/anyone-can-whistle",
"https://www.mtishows.com/the-apple-tree",
"https://www.mtishows.com/archy-mehitabel",
"https://www.mtishows.com/assassins",
"https://www.mtishows.com/avenue-q",
"https://www.mtishows.com/baby",
"https://www.mtishows.com/back-to-the-80s",
"https://www.mtishows.com/the-bakers-wife",
"https://www.mtishows.com/band-geeks",
"https://www.mtishows.com/band-geeks-expanded-cast-version",
"https://www.mtishows.com/the-bands-visit",
"https://www.mtishows.com/beautiful-the-carole-king-musical",
"https://www.mtishows.com/disneys-beauty-and-the-beast",
"https://www.mtishows.com/beetlejuice",
"https://www.mtishows.com/bendigo-boswell",
"https://www.mtishows.com/berlin-to-broadway-with-kurt-weill-a-musical-voyage",
"https://www.mtishows.com/the-big-one-oh",
"https://www.mtishows.com/big-the-musical",
"https://www.mtishows.com/billy-elliot-the-musical",
"https://www.mtishows.com/birds-of-paradise",
"https://www.mtishows.com/blame-it-on-the-movies",
"https://www.mtishows.com/bloody-bloody-andrew-jackson",
"https://www.mtishows.com/blues-in-the-night",
"https://www.mtishows.com/bonnie-clyde",
"https://www.mtishows.com/sandy-wilsons-the-boy-friend",
"https://www.mtishows.com/brandon-finds-his-star",
"https://www.mtishows.com/the-bridges-of-madison-county",
"https://www.mtishows.com/brigadoon-0",
"https://www.mtishows.com/bring-in-the-morning",
"https://www.mtishows.com/bring-it-on-the-musical",
"https://www.mtishows.com/bugsy-malone",
"https://www.mtishows.com/bullets-over-broadway-the-musical",
"https://www.mtishows.com/the-burnt-part-boys",
"https://www.mtishows.com/by-the-beautiful-sea",
"https://www.mtishows.com/camelot-small-cast-version",
"https://www.mtishows.com/camelot",
"https://www.mtishows.com/disneys-camp-rock-the-musical-one-act-edition",
"https://www.mtishows.com/candide-1974-version",
"https://www.mtishows.com/candide-1999-version",
"https://www.mtishows.com/canterbury-tales",
"https://www.mtishows.com/captain-stirrick",
"https://www.mtishows.com/caroline-or-change",
"https://www.mtishows.com/dr-seusss-the-cat-in-the-hat",
"https://www.mtishows.com/catch-me-if-you-can",
"https://www.mtishows.com/celebration",
"https://www.mtishows.com/a-charles-dickens-christmas",
"https://www.mtishows.com/charlie-and-the-chocolate-factory",
"https://www.mtishows.com/children-of-eden",
"https://www.mtishows.com/chitty-chitty-bang-bang",
"https://www.mtishows.com/a-christmas-carol-broadway-version",
"https://www.mtishows.com/the-christmas-schooner",
"https://www.mtishows.com/the-civil-war",
"https://www.mtishows.com/maltby-and-shires-closer-than-ever",
"https://www.mtishows.com/colette-collage",
"https://www.mtishows.com/come-from-away",
"https://www.mtishows.com/company",
"https://www.mtishows.com/barry-manilows-copacabana",
"https://www.mtishows.com/cry-baby",
"https://www.mtishows.com/cyrano",
"https://www.mtishows.com/daddy-long-legs",
"https://www.mtishows.com/damn-yankees",
"https://www.mtishows.com/the-day-before-spring",
"https://www.mtishows.com/dear-edwina",
"https://www.mtishows.com/disneys-descendants-the-musical",
"https://www.mtishows.com/dessa-rose",
"https://www.mtishows.com/dirty-rotten-scoundrels",
"https://www.mtishows.com/disaster",
"https://www.mtishows.com/disco-inferno",
"https://www.mtishows.com/divorce-me-darling",
"https://www.mtishows.com/do-you-wanna-dance",
"https://www.mtishows.com/do-you-wanna-dance-one-act-edition",
"https://www.mtishows.com/doctor-dolittle",
"https://www.mtishows.com/dogfight",
"https://www.mtishows.com/downriver",
"https://www.mtishows.com/dracula-the-musical",
"https://www.mtishows.com/drake",
"https://www.mtishows.com/the-drowsy-chaperone",
"https://www.mtishows.com/the-drunkard",
"https://www.mtishows.com/edges",
"https://www.mtishows.com/elephant-piggies-we-are-in-a-play",
"https://www.mtishows.com/elf-the-musical",
"https://www.mtishows.com/the-emperors-new-clothes-ahrens-flahertys",
"https://www.mtishows.com/ernest-in-love",
"https://www.mtishows.com/eubie",
"https://www.mtishows.com/fame-the-musical",
"https://www.mtishows.com/a-family-affair",
"https://www.mtishows.com/the-fantasticks",
"https://www.mtishows.com/fiddler-on-the-roof",
"https://www.mtishows.com/fiorello",
"https://www.mtishows.com/five-guys-named-moe",
"https://www.mtishows.com/the-fix",
"https://www.mtishows.com/follies",
"https://www.mtishows.com/follies-concert-version",
"https://www.mtishows.com/footprints-on-the-moon",
"https://www.mtishows.com/forever-plaid",
"https://www.mtishows.com/forever-plaid-plaid-tidings",
"https://www.mtishows.com/4-guys-named-jose-and-una-mujer-named-maria",
"https://www.mtishows.com/freaky-friday",
"https://www.mtishows.com/freaky-friday-one-act-edition",
"https://www.mtishows.com/freckleface-strawberry-the-musical",
"https://www.mtishows.com/freckleface-strawberry-the-musical-expanded-version",
"https://www.mtishows.com/freedom-train",
"https://www.mtishows.com/the-frogs",
"https://www.mtishows.com/the-full-monty",
"https://www.mtishows.com/a-funny-thing-happened-on-the-way-to-the-forum",
"https://www.mtishows.com/the-game-of-love",
"https://www.mtishows.com/a-gentlemans-guide-to-love-and-murder",
"https://www.mtishows.com/the-glorious-ones",
"https://www.mtishows.com/kurt-vonneguts-god-bless-you-mr-rosewater",
"https://www.mtishows.com/godspell",
"https://www.mtishows.com/godspell-2012",
"https://www.mtishows.com/goldilocks-and-the-three-bears",
"https://www.mtishows.com/the-goodbye-girl",
"https://www.mtishows.com/grand-hotel-the-musical",
"https://www.mtishows.com/greenwillow",
"https://www.mtishows.com/groundhog-day",
"https://www.mtishows.com/guys-and-dolls",
"https://www.mtishows.com/guys-and-dolls-concert-version",
"https://www.mtishows.com/hairspray",
"https://www.mtishows.com/hans-christian-andersen-0",
"https://www.mtishows.com/harry-connick-jrs-the-happy-elf",
"https://www.mtishows.com/happy-hunting",
"https://www.mtishows.com/heidi",
"https://www.mtishows.com/hello-my-baby",
"https://www.mtishows.com/honeymoon-in-vegas",
"https://www.mtishows.com/honk",
"https://www.mtishows.com/hot-mikado",
"https://www.mtishows.com/how-to-succeed-in-business-without-really-trying",
"https://www.mtishows.com/the-hunchback-of-notre-dame",
"https://www.mtishows.com/i-do-i-do",
"https://www.mtishows.com/i-do-i-do-i-do-i-do",
"https://www.mtishows.com/ifthen",
"https://www.mtishows.com/in-the-beginning",
"https://www.mtishows.com/in-transit",
"https://www.mtishows.com/into-the-woods",
"https://www.mtishows.com/it-shoulda-been-you",
"https://www.mtishows.com/jack-spratt-vc",
"https://www.mtishows.com/roald-dahls-james-and-the-giant-peach",
"https://www.mtishows.com/jane-eyre",
"https://www.mtishows.com/jekyll-hyde",
"https://www.mtishows.com/jekyll-and-hyde-youth-version",
"https://www.mtishows.com/john-jen",
"https://www.mtishows.com/junie-b-jones-the-musical",
"https://www.mtishows.com/just-so",
"https://www.mtishows.com/kean",
"https://www.mtishows.com/kinky-boots",
"https://www.mtishows.com/kismet",
"https://www.mtishows.com/knuffle-bunny-a-cautionary-musical",
"https://www.mtishows.com/lady-audleys-secret",
"https://www.mtishows.com/the-last-five-years",
"https://www.mtishows.com/leap-of-faith",
"https://www.mtishows.com/legally-blonde-the-musical",
"https://www.mtishows.com/les-miserables-0",
"https://www.mtishows.com/les-petits-rats",
"https://www.mtishows.com/let-em-eat-cake",
"https://www.mtishows.com/let-em-eat-cake-concert-version",
"https://www.mtishows.com/disneys-the-little-mermaid",
"https://www.mtishows.com/little-miss-sunshine",
"https://www.mtishows.com/a-little-night-music",
"https://www.mtishows.com/a-little-princess",
"https://www.mtishows.com/little-shop-of-horrors",
"https://www.mtishows.com/little-shop-of-horrors-broadway-version",
"https://www.mtishows.com/little-women",
"https://www.mtishows.com/loserville",
"https://www.mtishows.com/loves-labours-lost",
"https://www.mtishows.com/loving-repeating",
"https://www.mtishows.com/lucky-in-the-rain",
"https://www.mtishows.com/lucky-stiff",
"https://www.mtishows.com/magdalena",
"https://www.mtishows.com/the-main-street-kids-club-a-mathstart-musical",
"https://www.mtishows.com/make-me-a-song-the-music-of-william-finn",
"https://www.mtishows.com/mamma-mia",
"https://www.mtishows.com/a-man-of-no-importance",
"https://www.mtishows.com/marry-me-a-little",
"https://www.mtishows.com/disney-and-cameron-mackintoshs-mary-poppins",
"https://www.mtishows.com/roald-dahls-matilda-the-musical",
"https://www.mtishows.com/mean-girls",
"https://www.mtishows.com/merrily-we-roll-along",
"https://www.mtishows.com/meredith-willsons-miracle-on-34th-street-the-musical",
"https://www.mtishows.com/mirette",
"https://www.mtishows.com/miss-saigon",
"https://www.mtishows.com/moby-dick-the-musical",
"https://www.mtishows.com/the-most-happy-fella",
"https://www.mtishows.com/the-adventures-of-mr-toad",
"https://www.mtishows.com/murder-ballad",
"https://www.mtishows.com/the-music-man",
"https://www.mtishows.com/the-music-man-concert-version",
"https://www.mtishows.com/my-fair-lady",
"https://www.mtishows.com/my-favorite-year",
"https://www.mtishows.com/disneys-my-son-pinocchio-geppettos-musical-tale",
"https://www.mtishows.com/naked-mole-rat-gets-dressed-the-rock-experience",
"https://www.mtishows.com/new-girl-in-town",
"https://www.mtishows.com/newsies-0",
"https://www.mtishows.com/next-to-normal",
"https://www.mtishows.com/9-to-5-the-musical",
"https://www.mtishows.com/the-no-frills-revue",
"https://www.mtishows.com/of-thee-i-sing",
"https://www.mtishows.com/of-thee-i-sing-concert-version",
"https://www.mtishows.com/oh-coward",
"https://www.mtishows.com/oil-city-symphony",
"https://www.mtishows.com/oliver-0",
"https://www.mtishows.com/once",
"https://www.mtishows.com/once-on-this-island",
"https://www.mtishows.com/pacific-overtures",
"https://www.mtishows.com/paint-your-wagon",
"https://www.mtishows.com/the-pajama-game",
"https://www.mtishows.com/parade",
"https://www.mtishows.com/passion",
"https://www.mtishows.com/peter-and-the-starcatcher",
"https://www.mtishows.com/peter-pan-1954-broadway-version",
"https://www.mtishows.com/phantom-of-the-country-opera",
"https://www.mtishows.com/the-phantom-tollbooth",
"https://www.mtishows.com/philemon",
"https://www.mtishows.com/pippin",
"https://www.mtishows.com/boublil-and-schonbergs-the-pirate-queen-0",
"https://www.mtishows.com/the-pirates-of-penzance",
"https://www.mtishows.com/portable-pioneer-and-prairie-show",
"https://www.mtishows.com/pretty-woman-the-musical",
"https://www.mtishows.com/the-prince-and-the-pauper",
"https://www.mtishows.com/the-producers",
"https://www.mtishows.com/putting-it-together-1993-mtc-version",
"https://www.mtishows.com/putting-it-together-1999-broadway-version",
"https://www.mtishows.com/quilt-a-musical-celebration",
"https://www.mtishows.com/the-ragged-child",
"https://www.mtishows.com/ragtime-version-1",
"https://www.mtishows.com/ragtime-version-2",
"https://www.mtishows.com/rapunzel",
"https://www.mtishows.com/red-hot-and-cole",
"https://www.mtishows.com/redhead",
"https://www.mtishows.com/rent",
"https://www.mtishows.com/riverwind",
"https://www.mtishows.com/road-show",
"https://www.mtishows.com/roadside",
"https://www.mtishows.com/the-robber-bridegroom",
"https://www.mtishows.com/rock-nativity",
"https://www.mtishows.com/rocky",
"https://www.mtishows.com/the-roman-invasion-of-ramsbottom",
"https://www.mtishows.com/rothschild-sons",
"https://www.mtishows.com/rudolph-the-red-nosed-reindeer",
"https://www.mtishows.com/saturday-night",
"https://www.mtishows.com/the-scottsboro-boys",
"https://www.mtishows.com/scrooge-the-stingiest-man-in-town",
"https://www.mtishows.com/secrets-every-smart-traveler-should-know",
"https://www.mtishows.com/seussical",
"https://www.mtishows.com/seven-brides-for-seven-brothers",
"https://www.mtishows.com/1776",
"https://www.mtishows.com/she-loves-me",
"https://www.mtishows.com/she-persisted-the-musical",
"https://www.mtishows.com/shout-the-mod-musical-15",
"https://www.mtishows.com/showtune-celebrating-the-words-music-of-jerry-herman",
"https://www.mtishows.com/shrek-the-musical",
"https://www.mtishows.com/side-by-side-by-sondheim",
"https://www.mtishows.com/singin-in-the-rain",
"https://www.mtishows.com/sister-act",
"https://www.mtishows.com/six-women-with-brain-death-or-expiring-minds-want-to-know",
"https://www.mtishows.com/smike",
"https://www.mtishows.com/snapshots-a-musical-scrapbook",
"https://www.mtishows.com/dr-seusss-the-sneetches",
"https://www.mtishows.com/snow-white-rose-red-and-fred",
"https://www.mtishows.com/something-rotten",
"https://www.mtishows.com/sondheim-on-sondheim",
"https://www.mtishows.com/songs-for-a-new-world",
"https://www.mtishows.com/the-sound-of-plaid-the-glee-club-version-of-forever-plaid",
"https://www.mtishows.com/spookley-the-square-pumpkin-the-musical",
"https://www.mtishows.com/spring-awakening",
"https://www.mtishows.com/starting-here-starting-now",
"https://www.mtishows.com/the-story-of-my-life",
"https://www.mtishows.com/strike-up-the-band",
"https://www.mtishows.com/strike-up-the-band-concert-version",
"https://www.mtishows.com/sunday-in-the-park-with-george",
"https://www.mtishows.com/sweeney-todd",
"https://www.mtishows.com/talent-springs-eternal-fame-forever",
"https://www.mtishows.com/tarzan",
"https://www.mtishows.com/teddy-alice",
"https://www.mtishows.com/tenderloin",
"https://www.mtishows.com/the-theory-of-relativity-1",
"https://www.mtishows.com/13",
"https://www.mtishows.com/the-thirteen-clocks",
"https://www.mtishows.com/13-daughters",
"https://www.mtishows.com/thoroughly-modern-millie",
"https://www.mtishows.com/the-three-little-pigs",
"https://www.mtishows.com/tick-tick-boom",
"https://www.mtishows.com/timbuktu",
"https://www.mtishows.com/tin-pan-ali",
"https://www.mtishows.com/tintypes",
"https://www.mtishows.com/the-adventures-of-tom-sawyer",
"https://www.mtishows.com/tomfoolery",
"https://www.mtishows.com/the-whos-tommy",
"https://www.mtishows.com/tootsie",
"https://www.mtishows.com/the-toxic-avenger",
"https://www.mtishows.com/triumph-of-love",
"https://www.mtishows.com/the-25th-annual-putnam-county-spelling-bee",
"https://www.mtishows.com/the-unsinkable-molly-brown",
"https://www.mtishows.com/urinetown",
"https://www.mtishows.com/the-velveteen-rabbit",
"https://www.mtishows.com/violet",
"https://www.mtishows.com/waitress",
"https://www.mtishows.com/the-wedding-singer",
"https://www.mtishows.com/west-side-story",
"https://www.mtishows.com/western-star",
"https://www.mtishows.com/what-about-luv",
"https://www.mtishows.com/when-the-cookie-crumbles-you-can-still-pick-up-the-pieces",
"https://www.mtishows.com/wheres-charley",
"https://www.mtishows.com/andrew-lippas-wild-party",
"https://www.mtishows.com/wildcat-on-safari",
"https://www.mtishows.com/roald-dahls-willy-wonka",
"https://www.mtishows.com/wish-you-were-here",
"https://www.mtishows.com/women-on-the-verge-of-a-nervous-breakdown",
"https://www.mtishows.com/wonderland-high",
"https://www.mtishows.com/working",
"https://www.mtishows.com/working-2012-revised-version",
"https://www.mtishows.com/the-world-goes-round",
"https://www.mtishows.com/xanadu",
"https://www.mtishows.com/a-year-with-frog-and-toad",
"https://www.mtishows.com/youre-gonna-love-tomorrow",
"https://www.mtishows.com/young-frankenstein"
]

const names = [
"Elton John and Tim Rice's Aida",
"Ain't Misbehavin'",
"Disney's Aladdin Dual Language Edition",
"All in Love",
"The All Night Strut!",
"The All Night Strut! A Jumpin' Jivin' Jam",
"Amen Corner",
"Green Day's American Idiot",
"Annabelle Broom, The Unhappy Witch",
"Anne of Green Gables",
"Annie",
"Annie Warbucks",
"Anyone Can Whistle",
"The Apple Tree",
"Archy & Mehitabel",
"Assassins",
"Avenue Q",
"Baby",
"Back to the 80's",
"The Baker's Wife",
"Band Geeks",
"Band Geeks-Expanded Cast Version",
"The Band's Visit",
"Beautiful: The Carole King Musical",
"Disney's Beauty and the Beast",
"Beetlejuice",
"Bendigo Boswell",
"Berlin to Broadway with Kurt Weill A Musical Voyage",
"The Big One-Oh!",
"Big The Musical",
"Billy Elliot The Musical",
"Birds of Paradise",
"Blame It on the Movies!",
"Bloody Bloody Andrew Jackson",
"Blues in the Night",
"Bonnie & Clyde",
"Sandy Wilson's The Boy Friend",
"Brandon Finds His Star",
"The Bridges of Madison County",
"Brigadoon",
"Bring in the Morning",
"Bring It On The Musical",
"Bugsy Malone",
"Bullets over Broadway The Musical",
"The Burnt Part Boys",
"By the Beautiful Sea",
"Camelot - Small Cast Version",
"Camelot ",
"Disney's Camp Rock The Musical",
"Candide (1974 Version)",
"Candide (1999 Version)",
"Canterbury Tales",
"Captain Stirrick",
"Caroline, or Change",
"Dr. Seuss's The Cat in the Hat",
"Catch Me If You Can",
"Celebration",
"A Charles Dickens Christmas",
"Charlie And The Chocolate Factory",
"Children of Eden",
"Chitty Chitty Bang Bang",
"A Christmas Carol (Broadway Version)",
"The Christmas Schooner",
"The Civil War",
"Maltby and Shire's Closer Than Ever",
"Colette Collage",
"Come from Away",
"Company",
"Barry Manilow's Copacabana",
"Cry-Baby",
"Cyrano",
"Daddy Long Legs",
"Damn Yankees",
"The Day Before Spring",
"Dear Edwina",
"Disney's Descendants: The Musical",
"Dessa Rose",
"Dirty Rotten Scoundrels",
"Disaster!",
"Disco Inferno",
"Divorce Me, Darling!",
"Do You Wanna Dance?",
"Do You Wanna Dance? One-Act Edition",
"Doctor Dolittle",
"Dogfight",
"Downriver",
"Dracula The Musical",
"Drake",
"The Drowsy Chaperone",
"The Drunkard",
"Edges",
"Elephant & Piggie's 'We Are in a Play!'",
"Elf The Musical",
"The Emperor's New Clothes (Ahrens & Flaherty's)",
"Ernest in Love",
"Eubie!",
"Fame The Musical",
"A Family Affair",
"The Fantasticks",
"Fiddler on the Roof",
"Fiorello!",
"Five Guys Named Moe",
"The Fix",
"Follies",
"Follies (Concert Version)",
"Footprints on the Moon",
"Forever Plaid",
"Forever Plaid: Plaid Tidings",
"4 Guys Named José... and una Mujer Named María",
"Freaky Friday",
"Freaky Friday One-Act Edition",
"Freckleface Strawberry The Musical",
"Freckleface Strawberry The Musical (Expanded Version)",
"Freedom Train",
"The Frogs",
"The Full Monty",
"A Funny Thing Happened on the Way to the Forum",
"The Game of Love",
"A Gentleman's Guide to Love and Murder",
"The Glorious Ones",
"Kurt Vonnegut's God Bless You, Mr. Rosewater",
"Godspell",
"Godspell 2012",
"Goldilocks and the Three Bears",
"The Goodbye Girl",
"Grand Hotel: The Musical",
"Greenwillow",
"Groundhog Day",
"Guys and Dolls",
"Guys and Dolls (Concert Version)",
"Hairspray",
"Hans Christian Andersen                           ",
"Harry Connick, Jr.'s The Happy Elf",
"Happy Hunting",
"Heidi",
"Hello! My Baby",
"Honeymoon in Vegas",
"Honk!",
"Hot Mikado",
"How to Succeed in Business without Really Trying",
"The Hunchback of Notre Dame",
"I Do! I Do!",
"I Do! I Do! I Do! I Do!",
"If/Then",
"In the Beginning",
"In Transit",
"Into the Woods",
"It Shoulda Been You",
"Jack Spratt, VC",
"Roald Dahl's James and the Giant Peach",
"Jane Eyre",
"Jekyll & Hyde",
"Jekyll and Hyde (Youth Version)",
"John & Jen",
"Junie B. Jones, The Musical",
"Just So",
"Kean",
"Kinky Boots",
"Kismet",
"Knuffle Bunny: A Cautionary Musical",
"Lady Audley's Secret",
"The Last Five Years",
"Leap of Faith",
"Legally Blonde The Musical",
"Les Misérables",
"Les Petits Rats",
"Let 'Em Eat Cake",
"Let 'Em Eat Cake (Concert Version)",
"Disney's The Little Mermaid",
"Little Miss Sunshine",
"A Little Night Music",
"A Little Princess",
"Little Shop of Horrors",
"Little Shop of Horrors - Broadway Version",
"Little Women",
"Loserville",
"Love's Labour's Lost",
"Loving Repeating",
"Lucky in the Rain",
"Lucky Stiff",
"Magdalena",
"The Main Street Kids' Club: A MathStart Musical",
"Make Me a Song: The Music of William Finn",
"Mamma Mia!",
"A Man of No Importance",
"Marry Me a Little",
"Disney and Cameron Mackintosh's Mary Poppins",
"Roald Dahl's Matilda The Musical",
"Mean Girls",
"Merrily We Roll Along",
"Meredith Willson's Miracle on 34th Street The Musical",
"Mirette",
"Miss Saigon",
"Moby Dick! The Musical",
"The Most Happy Fella",
"The Adventures of Mr. Toad",
"Murder Ballad",
"The Music Man",
"The Music Man (Concert Version)",
"My Fair Lady",
"My Favorite Year",
"Disney's My Son Pinocchio: Geppetto's Musical Tale",
"Naked Mole Rat Gets Dressed: The Rock Experience",
"New Girl in Town",
"Newsies",
"Next to Normal",
"9 to 5 The Musical",
"The No-Frills Revue",
"Of Thee I Sing",
"Of Thee I Sing (Concert Version)",
"Oh, Coward!",
"Oil City Symphony",
"Oliver!",
"Once",
"Once on This Island",
"Pacific Overtures",
"Paint Your Wagon ",
"The Pajama Game",
"Parade",
"Passion",
"Peter and the Starcatcher",
"Peter Pan (1954 Broadway Version)",
"Phantom of the Country Opera",
"The Phantom Tollbooth",
"Philemon",
"Pippin",
"Boublil And Schönberg's The Pirate Queen       ",
"The Pirates of Penzance",
"Portable Pioneer and Prairie Show",
"Pretty Woman: The Musical",
"The Prince and the Pauper",
"The Producers",
"Putting It Together (1993 MTC Version)",
"Putting It Together (1999 Broadway Version)",
"Quilt, A Musical Celebration",
"The Ragged Child",
"Ragtime (Version 1)",
"Ragtime (Version 2)",
"Rapunzel",
"Red Hot and Cole",
"Redhead",
"Rent",
"Riverwind",
"Road Show",
"Roadside",
"The Robber Bridegroom",
"Rock Nativity",
"Rocky",
"The Roman Invasion of Ramsbottom",
"Rothschild & Sons                                 ",
"Rudolph The Red-Nosed Reindeer",
"Saturday Night",
"The Scottsboro Boys",
"Scrooge, The Stingiest Man in Town",
"Secrets Every Smart Traveler Should Know",
"Seussical",
"Seven Brides for Seven Brothers",
"1776",
"She Loves Me",
"She Persisted, The Musical",
"SHOUT! The Mod Musical",
"Showtune: Celebrating the Words & Music of Jerry Herman",
"Shrek The Musical",
"Side by Side by Sondheim",
"Singin' in the Rain",
"Sister Act",
"Six Women with Brain Death or Expiring Minds Want to Know ",
"Smike",
"Snapshots: A Musical Scrapbook",
"Dr. Seuss's The Sneetches",
"Snow White, Rose Red (and Fred)",
"Something Rotten!",
"Sondheim on Sondheim",
"Songs for a New World",
"The Sound of Plaid: The Glee Club Version of Forever Plaid",
"Spookley The Square Pumpkin: The Musical",
"Spring Awakening",
"Starting Here, Starting Now",
"The Story of My Life",
"Strike up the Band",
"Strike up the Band (Concert Version)",
"Sunday in the Park with George",
"Sweeney Todd",
"Talent Springs Eternal – Fame Forever",
"Tarzan",
"Teddy & Alice",
"Tenderloin",
"The Theory of Relativity",
"13",
"The Thirteen Clocks",
"13 Daughters",
"Thoroughly Modern Millie",
"The Three Little Pigs",
"Tick, Tick... Boom!",
"Timbuktu!",
"Tin Pan Ali",
"Tintypes",
"The Adventures of Tom Sawyer",
"Tomfoolery",
"The Who's Tommy",
"Tootsie",
"The Toxic Avenger",
"Triumph of Love",
"The 25th Annual Putnam County Spelling Bee",
"The Unsinkable Molly Brown",
"Urinetown",
"The Velveteen Rabbit",
"Violet",
"Waitress",
"The Wedding Singer",
"West Side Story",
"Western Star",
"What about Luv?",
"When the Cookie Crumbles, You Can Still Pick up the Pieces ",
"Where's Charley?",
"Andrew Lippa's Wild Party",
"Wildcat on Safari",
"Roald Dahl's Willy Wonka",
"Wish You Were Here",
"Women on the Verge of a Nervous Breakdown",
"Wonderland High",
"Working",
"Working (2012 Revised Version)",
"The World Goes 'Round",
"Xanadu",
"A Year with Frog and Toad",
"You're Gonna Love Tomorrow",
"Young Frankenstein"
]

module.exports = mtiLinks
